name: Extract data from sources

on:
    schedule:
      # * is a special character in YAML so you have to quote this string
      - cron:  '30 5 * * *'
    workflow_dispatch:
jobs:
  extract_data:
    environment: dev
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: pip
      - name: Checkout code
        uses: nschloe/action-cached-lfs-checkout@v1
        with:
          include: "*.bin"
      - name: Install dependencies and project
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-dev --no-interaction --no-ansi
      - name: Extract data using getters
        env:
          REDDIT_USER_AGENT: ${{ vars.REDDIT_USER_AGENT }}
          DATA_SOURCES: ${{ vars.DATA_SOURCES }}
          X_ACCOUNTS: ${{ vars.X_ACCOUNTS }}
          BING_SUBSCRIPTION_KEY: ${{ vars.BING_SUBSCRIPTION_KEY }}
          TWITTER_TOKEN: ${{ vars.X_TOKEN }}
          OPENAI_API_KEY: ${{ vars.OPENAI_API_KEY }}
        run: poetry run python scripts/extract_data.py
      - name: Ingest articles to DEVs
        env:
          MONGODB_USERNAME: ${{ vars.MONGODB_USERNAME }}
          MONGODB_PASSWORD: ${{ vars.MONGODB_PASSWORD_DEV }}
          MONGODB_HOST: ${{ vars.MONGODB_HOST_DEV }}
        run: poetry run python scripts/ingest_articles.py
      - name: Ingest articles to PROD
        env:
          MONGODB_USERNAME: ${{ vars.MONGODB_USERNAME }}
          MONGODB_PASSWORD: ${{ vars.MONGODB_PASSWORD_PROD }}
          MONGODB_HOST: ${{ vars.MONGODB_HOST_PROD }}
        run: poetry run python scripts/ingest_articles.py
      - name: Trigger Topic Modeling
        uses: peter-evans/repository-dispatch@v3
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            event-type: topic-modeling-event
