repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-ast
      - id: check-yaml
      - id: check-toml
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: local
    hooks:
    - id: black
      name: formatting
      entry: black
      language: system
      types: [python]
    - id: mypy
      name: typing
      entry: mypy
      language: system
      types: [python]
    - id: isort
      name: import-sorting
      entry: isort --profile black
      language: system
      types: [python]
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      require_serial: true
